# This is a basic workflow to help you get started with Actions

name: STR FILE MAKER

# Controls when the workflow will run
on:
  # Triggers the workflow on push
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# The Jobs
jobs:
  makeDat:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # install strfile, its part of mod-fortune
      - name: install strfile
        run: sudo apt-get install -y fortune
        
        # Remove the Old .dat file,
      - name: remove old .dat file
        run: rm postive.dat
        continue-on-error: true
        
        # run strfile on the postive file, use loops for more files in the future?
      - name: run strfile
        run: strfile postive
        
        # Now we push the change
      - name: Push The File
        run: |
          git config --global user.name 'LakesideMiners'
          git config --global user.email '23389169+LakesideMiners@users.noreply.github.com'
          git commit -am "creating strfile"
          git push
